### ISSUE TITLE
AuthenticationCancelled thrown

### ISSUE THREAD

**Issue by ViktorBergman** [OneDrive/onedrive-sdk-csharp#158] opened 2016-08-28 19:48 UTC
Using the latest 2.0 package I cannot sign in into OneDrive for Consumer:

```csharp
string[] scopes = new string[] { "onedrive.appfolder", "offline_access", "wl.signin","onedrive.readonly" };
var msaAuthProvider = new MsaAuthenticationProvider("XXXX", "https://login.live.com/oauth20_desktop.srf", scopes);
await msaAuthProvider.AuthenticateUserAsync();
return new OneDriveClient("https://api.onedrive.com/v1.0", msaAuthProvider);
```

AuthenticationCancelled is immediately thrown although no user interface is even presented that supposedly would cancel the authentication?

(edited for readability)

**Comment by mhomde** [comment] 2016-08-28 23:50
Yeah, I'm having the same problem, there's more in this issue 

https://github.com/OneDrive/onedrive-sdk-dotnet-msa-auth-adapter/issues/3#issuecomment-242955155

**Comment by davideloper** [comment] 2016-08-29 07:03
The same problem on my side  (Microsoft.Graph.ServiceException, Code: authenticationCancelled).

**Comment by davideloper** [comment] 2016-08-29 12:32
So, anyone knows the solution (except downgrading SDK version)? Does Microsoft know for this problem?

**Comment by cdmayer** [comment] 2016-08-29 16:58
I'm able to reproduce locally. Investigating...

**Comment by cdmayer** [comment] 2016-08-29 23:06
I suspect there is a packaging issue, but am having trouble verifying. Can someone that is hitting this issue check this: what version of `Microsoft.IdentityModel.Clients.ActiveDirectory` do you have installed? If >3.0, can you try downgrading to 2.13.xx and try again? Please let me know the results.

**Comment by cdmayer** [comment] 2016-08-29 23:12
Also helpful would be if someone hitting this issue were to post their complete code (at least the relevant parts). I am unable to reproduce locally, even after setting up a fresh environment.

**Comment by mhomde** [comment] 2016-08-29 23:49
Have you tried compiling a windows store app in release mode  with .net native enabled? I found it worked most times locally otherwise

**Comment by cdmayer** [comment] 2016-08-30 00:21
Targeting .NET Native does cause some issues, but this is no surprise since there is no serialization configuration, as is required (https://msdn.microsoft.com/en-us/library/dn600638(v=vs.110).aspx).

@ViktorBergman @davideloper Are you building in Debug or Release mode?

**Comment by mhomde** [comment] 2016-08-30 01:25
Yeah, unfortunately not much choice if you want to publish through the store :)

**Comment by davideloper** [comment] 2016-08-30 07:10
Tried to build in Release mode - the error still exists. So, I' m developing UWP app, VS 2015, I 've installed Microsoft.IdentityModel.Clients.ActiveDirectory and tried with both versions (3.xx, 2.13.xx), with no success. Basicly, I think, I do not need this package.
The code:
var msaAuthenticationProvider = new MsaAuthenticationProvider(CLIENT_ID, "https://login.live.com/oauth20_desktop.srf", new[] { "onedrive.readonly", "wl.signin", "wl.offline_access" });
await msaAuthenticationProvider.AuthenticateUserAsync();

**Comment by dpaulino** [comment] 2016-08-30 23:51
```
Task authTask = null; 

if (oneDriveClient == null)
{
  var msaAuthProvider = new MsaAuthenticationProvider(clientId, returnUrl, scopes);
  oneDriveClient = new OneDriveClient(baseUrl, msaAuthProvider);
  authTask = msaAuthProvider.AuthenticateUserAsync();
  AuthProvider = msaAuthProvider;
}
try
{
  await authTask;
}
catch (ServiceException e)
{
  Debug.WriteLine(e);
}
```

I am having the exact same exception. Above is my code. This code was taken almost exactly from the official UWP sample. No changes in user interface on the app during debugging either. 

Nuget packages installed: Microsoft.OnedriveSDK v2.0.0, and Microsoft.OneDriveSdk.Authentication v1.0.1

**Comment by davideloper** [comment] 2016-08-31 06:38
Any news here @cdmayer ? Thanks in advance.

**Comment by cdmayer** [comment] 2016-08-31 16:28
Investigating with high priority. To be clear, I am investigating issues that arise during authentication when .NET Native is enabled (this usually happens by default for Release builds). Will report back when I have news.

**Comment by davideloper** [comment] 2016-08-31 19:50
Is 'm not sure if this is really the problem. In app properties I have Active (debug) Configuration selected, and checkbox Compile with .NET Native tool chain unchecked. Should we try with some other settings or build properties?

**Comment by cdmayer** [comment] 2016-08-31 22:45
I'm still working on this. You can see the latest in this branch: https://github.com/OneDrive/onedrive-sdk-dotnet-msa-auth-adapter/tree/async-updates

It would appear that if you build the branch that I linked (above) and reference the binaries directly from your project, everything should work. I am running into issues where packing it into a Nuget package still does not work. For now, please try cloning the above branch, building the binaries, and referencing them directly.

**Comment by mhomde** [comment] 2016-09-01 00:16
The error doesn't happen to be related to this? http://stackoverflow.com/questions/38321069/json-serialization-error-when-updating-user-in-azure-ad-via-graph

**Comment by Marccnl** [comment] 2016-09-01 06:26
I'm developing an UWP application and am experiencing the same problem but found that this only occurs when i run the app on my laptop. When i deploy it to my phone the login popup does show and it works as expected, either in debug or in release mode.

**Comment by ViktorBergman** [comment] 2016-09-06 07:05
Probably OT but I'm finding it hard to be convinced as to why the breaking changes in 2.0 is worth upgrading. So, can anyone give us the elevator pitch for upgrading to 2.0?

**Comment by cdmayer** [comment] 2016-09-07 15:40
Sorry for the delay all, but I am still working on the solution here.

@ViktorBergman, V2 was refactored to work with Graph.Core, which centralized things like `AuthenticationProvider` and other components that _any_ SDK/library accessing Graph (really, OData API)  would need. V1 was almost an exact duplicate of the Graph.Core components (and in reality the latter was based on the former), and we didn't want to maintain two versions of the same code, so V2 was born.

For now, there is no big reason to move to V2. You can keep using V1 as-is and it will be fine. However, moving forward all new features and non-critical bugfixes will only target V2, so at some point it will be natural to move over to V2. Once these authentication issues are resolved, there should be little reason not to move over anyway because the code changes are minimal. If you disagree strongly, I would love to hear why!

**Comment by cdmayer** [comment] 2016-09-07 15:41
@mhomde I don't believe that is related. Do you have reason to believe it is?

**Comment by cdmayer** [comment] 2016-09-07 19:25
I have a candidate fix in this branch: https://github.com/OneDrive/onedrive-sdk-dotnet-msa-auth-adapter/tree/async-updates

Please try cloning this branch, building the binaries, then referencing them directly from your project (in place of the Nuget package). It solves the `authenticationCancelled` issue on .NET Native for me, so I would love some verification.

**Comment by cdmayer** [comment] 2016-09-07 23:00
New binaries are signed and uploaded to [NuGet](https://www.nuget.org/packages/Microsoft.OneDriveSDK.Authentication/1.0.2). Please try installing 1.0.2 of the Auth Adapter and let me know if it fixes your issue.

**Comment by dpaulino** [comment] 2016-09-08 04:29
@cdmayer thanks. going to try this soon and report back

**Comment by Marccnl** [comment] 2016-09-08 12:36
works for me, thanks!

**Comment by mhomde** [comment] 2016-09-08 13:14
Hmm, I still seem to have the same problem when compiling for .Net Native on desktop

**Comment by davideloper** [comment] 2016-09-08 14:02
Works for me too, thanks.
I had to remove OneDrive sdk and OneDrive.Authentication and add them back to project.

**Comment by cdmayer** [comment] 2016-09-08 14:35
@mhomde can you try uninstalling the old package installing the new one? Make sure it's 1.0.2.

If you are still having issues, please try adding this code where you invoke `AuthenticateAsync`:

```csharp
            try
            {
                result = await authUi.AuthenticateAsync(requestUri, callbackUri);
            }
            catch (ServiceException ex)
            {
                var message = ex.Error.Code + ": " + ex.Error.Message;
                throw;
            }
```

Then insert a break point at the `throw` line and tell me the value of `message`.

**Closed** 2016-09-08 16:00 UTC

**Comment by mhomde** [comment] 2016-09-12 07:44
Sorry for delay, wanted to publish through the store to make sure, and it seems to work 
https://www.microsoft.com/store/apps/9nblggh51jvk  

Good job fixing the bug, thanks! Lots of cool possibilities with  the OneDrive SDK, only thing I'm missing is real-time notifications
