### ISSUE TITLE
OneDrive Service don't get a refresh token

### ISSUE THREAD

**Issue by NPadrutt** [OneDrive/onedrive-sdk-csharp#178] opened 2016-10-05 12:30 UTC
Hi

I know that it is not the 100% correct place to ask this question. But I thought I have the biggest chance to get an appropriate answer since you guys are the experts for the onedrive service. 

I use Xamarin.Auth to authenticate with the OneDrive Service. This worked fine for a while now, but I seems there where changes on the service so it stopped working.. I upgraded to the new version 2.0 and try to make it work again. The Initial authentication works well so far. But after a while it always started to crash. I realized that there isn't any refrehs token sent back from the onedrive service.

This is the code to call the Auth UI:
   private Task<IDictionary<string, string>> ShowWebView()
    {
        var tcs = new TaskCompletionSource<IDictionary<string, string>>();

        var auth = new OAuth2Authenticator(ServiceConstants.MSA_CLIENT_ID,
            string.Join(",", ServiceConstants.Scopes),
            new Uri(GetAuthorizeUrl()),
            new Uri(ServiceConstants.RETURN_URL));

        auth.Completed +=
            (sender, eventArgs) =>
            {
                tcs.SetResult(eventArgs.IsAuthenticated ? eventArgs.Account.Properties : null);
            };

        var intent = auth.GetUI(Application.Context);
        intent.SetFlags(ActivityFlags.NewTask);

        Application.Context.StartActivity(intent);

        return tcs.Task;
    }

    private string GetAuthorizeUrl()
    {
        var requestUriStringBuilder = new StringBuilder();
        requestUriStringBuilder.Append(ServiceConstants.AUTHENTICATION_URL);
        requestUriStringBuilder.AppendFormat("?{0}={1}", ServiceConstants.REDIRECT_URI,
            ServiceConstants.RETURN_URL);
        requestUriStringBuilder.AppendFormat("&{0}={1}", ServiceConstants.CLIENT_ID,
            ServiceConstants.MSA_CLIENT_ID);
        requestUriStringBuilder.AppendFormat("&{0}={1}", ServiceConstants.SCOPE,
            WebUtility.UrlEncode(string.Join(" ", ServiceConstants.Scopes)));
        requestUriStringBuilder.AppendFormat("&{0}={1}", ServiceConstants.RESPONSE_TYPE, ServiceConstants.CODE);

        return requestUriStringBuilder.ToString();
    } 

The Authorize URI is:

`https://login.live.com/oauth20_authorize.srf?redirect_uri=https://login.live.com/oauth20_desktop.srf&client_id=["id"]&scope=onedrive.readwrite+wl.offline_access+wl.signin&response_type=code`

The response I get contains 6 Elements:

```
access_token: "EwAIA..."
token_type: "bearer"
expires_in: "3600"
scope: "onedrive.readwrite wl.offline_access wl.signin wl.basic wl.skydrive wl.skydrive_update onedrive.readonly"
user_id: "41...."
state: "ykjfmttehzjebqtp"
```
When I check it with the Documentation (https://dev.onedrive.com/auth/msa_oauth.htm) I can't see what's wrong here. Any ideas?

**Comment by cdmayer** [comment] 2016-10-05 23:29
This seems like a dupe of https://github.com/OneDrive/onedrive-api-docs/issues/455, except this is MSA instead of AAD. Does the access token that you acquire work for the first hour (i.e. before it expires)?

**Comment by NPadrutt** [comment] 2016-10-06 07:06
It sounds like the same issue, but it is a MSA. Is there any news on this?

**Comment by cdmayer** [comment] 2016-10-12 15:54
This is definitely not an SDK issue. Please use https://github.com/OneDrive/onedrive-api-docs/issues/455 to get this resolved.

**Closed by cdmayer** 2016-10-12 15:54 UTC
