### ISSUE TITLE
Search does not list matched items of sub folder

### ISSUE THREAD

**Issue by prakashguru** [OneDrive/onedrive-sdk-csharp#107] opened 2016-04-10 17:11 UTC
Hi,

I have a problem with a search api. I am not sure whether it is problem from my approach or the search api itself. I am using a one drive for business.

The "data" term is available as a file name in root folder and subfolder as shown below.
**Root**
| - Data Science.docx
| - GKK
----| - Matrix Data.xlsx
----| - Data Science (1).docx.        

`
_oneDriveClient.Drive.Root.Search("data").Request().Top(100).Select("name,id,lastModifiedDateTime,folder,size").GetAsync()
`

But the above search api call returns only two items. The first is the "Data Science.docx" and the second is the "GKK" folder!!. The matched files inside the GKK folder are not listed!!!

As per the https://dev.onedrive.com/items/search.htm, _**"Search returns matching results from the item specified in the URL and all children of that item"**_

Looks like I am missing something. I tried to use the IItemSearchRequest.Expand() but it resulted in an error.

Is there way to get search working for the above scenario?

**Comment by ginach** [comment] 2016-04-12 01:11
Hi @prakashguru,

Search should return a flattened list of items that meet search criteria, not the behavior you're seeing. Since this is an API issue could you move this over to the [API docs repo](https://github.com/OneDrive/onedrive-api-docs/issues)?

**Comment by katahir** [comment] 2016-04-12 01:19
Hey Prakash,
Search is supposed to return a flat list of files and folders. The parent item is not included unless it matches the search criteria itself. What you are seeing is definitely not the intended behavior. Can you please send me the request response pair, including any headers you send/receive from the api?

You can email me the above info at katahir@microsoft.com.

**Comment by ginach** [comment] 2016-06-30 21:49
@prakashguru, this was a bug in the API that should be fixed now.

**Closed by ginach** 2016-06-30 21:49 UTC
