### ISSUE TITLE
SilentlyAuthenticatedMicrosoftAccountClient can not sign out

### ISSUE THREAD

**Issue by JimiC** [OneDrive/onedrive-sdk-csharp#55] opened 2016-01-15 17:45 UTC
If you create a client with an account session from the cache (`SilentlyAuthenticatedMicrosoftAccountClient`) the `CanSignOut` is not set to `true`, therefore the client can't revoke the access.

This can be resolved by adding at line 193 in `AuthenticationProvider.ProcessCachedAccountSessionAsync` the following code:
```
accountSession.CanSignOut = true;
```

**Comment by ginach** [comment] 2016-01-15 18:10
Thanks for reporting this, the fix is rolled into my current PR.

**Comment by JimiC** [comment] 2016-01-15 19:04
Just to make things easier for you, in your PR it has to be added in line 252.

**Comment by ginach** [comment] 2016-01-15 20:22
No, the PR will fix the issue correctly. The cache stores the full contents of the account session blobs in JSON format so if CanSignOut is set to true at time of session creation it will be stored as such in the cache. The issue is at the time of creating those account sessions, which we do in SendTokenRequestAsync, we aren't currently setting the value of CanSignOut to true. My change in the PR fixes that.

**Comment by ginach** [comment] 2016-01-15 23:24
This is fixed in version 1.1.29. Please re-open if you're still seeing issues.

**Closed by ginach** 2016-01-15 23:24 UTC
Labels: bug

**Comment by JimiC** [comment] 2016-01-15 23:54
Confirming it's fixed. :+1:
